

-- 模块名 = "模块路径" ,
-- 关联模块所在路径



GuiWindowList = 
{
    CommonWindow					= "GuiSystem.WindowList.CommonWindow.CommonWindow" ,	-- 逻辑窗口背景,不能单独创建
    LoginWindow						= "GuiSystem.WindowList.LoginWindow",					-- 账号登陆窗体
	RegisterWindow					= "GuiSystem.WindowList.RegisterWindow" ,				-- 账号注册窗体
    PackWindow						= "GuiSystem.WindowList.PackWindow" ,					-- 背包界面
    SelectRoleWindow				= "GuiSystem.WindowList.SelectRoleWindow" ,				-- 角色选择界面
    NameTitleWindow					= "GuiSystem.WindowList.NameTitleWindow" ,				-- 头顶名字界面
	MainLeftTopWindow				= "GuiSystem.WindowList.MainLeftTopWindow" ,			-- 主界面左边上部窗口
	MainLeftCenterWindow			= "GuiSystem.WindowList.MainLeftCenterWindow" ,			-- 主界面左边中部窗口
	MainLeftBottomWindow			= "GuiSystem.WindowList.MainLeftBottomWindow" ,			-- 主界面左边下部窗口
	MainMidBottomWindow				= "GuiSystem.WindowList.MainMidBottomWindow" ,			-- 主界面中间下部窗口
	MainRightBottomWindow			= "GuiSystem.WindowList.MainRightBottomWindow" ,		-- 主界面右边下部窗口
	MainRightTopWindow				= "GuiSystem.WindowList.MainRightTopWindow" ,			-- 主界面右边上部窗口
	CreateRoleWindow				= "GuiSystem.WindowList.CreateRoleWindow" ,				-- 创建角色界面
	MakeFaceWindow					= "GuiSystem.WindowList.MakeFaceWindow" ,				-- 脸部处理界面
	MaterialComposeWindow           = "GuiSystem.WindowList.MaterialComposeWindow",         -- 材料合成窗口
	NumericKeypadWindow             = "GuiSystem.WindowList.NumericKeypadWindow",           -- 数字小键盘窗口
	RoleViewWindow                  = "GuiSystem.WindowList.RoleViewWindow",                -- 查看角色窗口
	HeadTitleWindow                 = "GuiSystem.WindowList.HeadTitleWindow",               -- 头衔系统窗口
	WildHangupWindow                = "GuiSystem.WindowList.WildHangupWindow",               --野外挂机窗口
	WareRenameWindow				= "GuiSystem.WindowList.WareRenameWindow",				-- 仓库重命名窗口
	TipsWindow				        = "GuiSystem.WindowList.TipsWindow",				    -- 仓库重命名窗口
	EquipTooltipsWindow				= "GuiSystem.WindowList.EquipTooltipsWindow",			-- 装备Tooltips窗口
	GoodsTooltipsWindow				= "GuiSystem.WindowList.GoodsTooltipsWindow",			-- 物品Tooltips窗口
	PlayerWindow					= "GuiSystem.WindowList.PlayerWindow",					-- 人物窗口
	DidaWindow						= "GuiSystem.WindowList.DidaWindow",					-- 消息滴答窗口
	ChatSystemTipsWindow			= "GuiSystem.WindowList.ChatSystemTipsWindow",			-- 物品消息窗口
	TipsActorAboveWindow			= "GuiSystem.WindowList.TipsActorAboveWindow",			-- 系统消息窗口
	TipsActorUnderWindow			= "GuiSystem.WindowList.TipsActorUnderWindow",			-- 系统消息窗口
	ChatWindow						= "GuiSystem.WindowList.ChatWindow",					-- 频道聊天窗口
	SpeechNoticeWindow				= "GuiSystem.WindowList.SpeechNoticeWindow",			-- 语音状态显示窗口
	FightBloodWindow				= "GuiSystem.WindowList.Fight.FightBloodWindow",		-- 飘血窗口
	HuoDongWindow 					= "GuiSystem.WindowList.HuoDongWindow",  			 	-- 活动窗口
	CommonGuideWindow 				= "GuiSystem.WindowList.CommonWindow.CommonGuideWindow",-- 规则描述窗口
	HuoDongPushWindow 				= "GuiSystem.WindowList.HuoDongPushWindow", 		    -- 活动推送窗口
	HuoDongCalenderWindow   		= "GuiSystem.WindowList.HuoDongCalenderWindow",      	-- 活动日历窗口
	ShopWindow						= "GuiSystem.WindowList.ShopWindow",					-- 商城主窗口
	PetWindow						= "GuiSystem.WindowList.PetWindow",						-- 灵兽主窗口
	PetLookWindow					= "GuiSystem.WindowList.PetLookWindow",						-- 查看灵兽窗口
	PetBreedWindow					= "GuiSystem.WindowList.PetBreedWindow",						-- 灵兽繁殖窗口
	DialogModelWindow				= "GuiSystem.WindowList.DialogModelWindow",    			-- 任务对白情景窗口
	DialogScenarioWindow			= "GuiSystem.WindowList.DialogScenarioWindow",    		-- 剧情对话窗口 npc
	NotificationBottomWindow		= "GuiSystem.WindowList.NotificationBottomWindow",    	-- 公告信息窗口
	NotificationBattleWindow		= "GuiSystem.WindowList.NotificationBattleWindow",    	-- 战斗信息窗口
	ChatSettingWindow				= "GuiSystem.WindowList.ChatSettingWindow",    			-- 聊天设置窗口
	ChatHistoryWindow				= "GuiSystem.WindowList.ChatHistoryWindow",    			-- 聊天输入历史窗口
	TiShiBattleUpWindow				= "GuiSystem.WindowList.TiShiBattleUpWindow",			-- 战力增加的提示窗口
	SceneMapWindow 					= "GuiSystem.WindowList.SceneMapWindow",   				-- 场景地图窗口
    WorldMapWindow                  = "GuiSystem.WindowList.WorldMapWindow",                -- 世界地图窗口
    InputOperateWindow              = "GuiSystem.WindowList.InputOperateWindow",            -- 输入事件层窗口
	NarratorWindow 					= "GuiSystem.WindowList.NarratorWindow",   				-- 旁白窗口
    ItemUseWindow              		= "GuiSystem.WindowList.ItemUseWindow",            		-- 使用物品窗口
	SpecialItemUseWindow            = "GuiSystem.WindowList.SpecialItemUseWindow",          -- 特殊使用物品窗口(比如寻宝图)
    MainTaskWindow              	= "GuiSystem.WindowList.MainTaskWindow",            	-- 任务窗口
    SpeakerWindow              		= "GuiSystem.WindowList.SpeakerWindow",            		-- 喇叭显示窗口
    SpeakerSendWindow              	= "GuiSystem.WindowList.SpeakerSendWindow",            	-- 喇叭发送窗口
	MiniMapWindow 				    = "GuiSystem.WindowList.MiniMapWindow",					-- 小地图窗口
	LoadingWindow 				    = "GuiSystem.WindowList.LoadingWindow",					-- 加载界面
	ProgressBarWindow 				= "GuiSystem.WindowList.ProgressBarWindow",				-- 进度条条窗口
	ForgeWindow 				    = "GuiSystem.WindowList.ForgeWindow",					-- 打造窗口
	TeamWindow						= "GuiSystem.WindowList.TeamWindow",					-- 组队窗口
	TeamGoalsWindow					= "GuiSystem.WindowList.TeamGoalsWindow",				-- 队伍目标窗口
	ContextMenuWindow				= "GuiSystem.WindowList.ContextMenuWindow",				-- 队伍目标窗口
	TeamInviteFriendsWindow			= "GuiSystem.WindowList.TeamInviteFriendsWindow",		-- 组队系统邀请玩家窗口
	TeamTalkWindow					= "GuiSystem.WindowList.TeamTalkWindow",				-- 组队系统喊话窗口
	TeamTalkHistoryWindow			= "GuiSystem.WindowList.TeamTalkHistoryWindow",			-- 组队系统喊话历史记录窗口
	DragonBallWindow				= "GuiSystem.WindowList.DragonBallWindow",				-- 七龙珠窗口
	RichTextWindow					= "GuiSystem.WindowList.RichTextWindow",				-- 富文本窗口
	TeamApplyListWindow				= "GuiSystem.WindowList.TeamApplyListWindow",			-- 组队申请列表窗口
	TeamShowPanelWindow				= "GuiSystem.WindowList.TeamShowPanelWindow",			-- 组队显示面板窗口		
	ReliveWindow					= "GuiSystem.WindowList.ReliveWindow",					-- 复活窗口	
	CommonNoticeWindow             	= "GuiSystem.WindowList.CommonNoticeWindow",			-- 通用提示信息窗口
	ShadeImageWindow               	= "GuiSystem.WindowList.ShadeImageWindow",				-- 主界面背景阴影
	ChipExchangeWindow             	= "GuiSystem.WindowList.ChipExchangeWindow",			-- 通用商店
	ShadeImageWindow               	= "GuiSystem.WindowList.ShadeImageWindow",				-- 主界面背景阴影
	ClanNoneWindow                 	= "GuiSystem.WindowList.ClanNoneWindow"	,				-- 帮派（未拥有）窗口
	ClanOwnWindow                  	= "GuiSystem.WindowList.ClanOwnWindow"	,				-- 帮派（已拥有）窗口
	ClanCourseWindow               	= "GuiSystem.WindowList.Clan.ClanOwn.ClanCourseWindow",				--帮派历程窗口
	ClanApplyListWindow            	= "GuiSystem.WindowList.Clan.ClanOwn.ClanApplyListWindow",			--帮派申请列表窗口
	ClanSettingsWindow             	= "GuiSystem.WindowList.Clan.ClanOwn.ClanSettingsWindow"	,		--帮派设置窗口
	ClanWelcomeNewWindow           	= "GuiSystem.WindowList.Clan.ClanOwn.ClanWelcomeNewWindow",			--帮派迎新窗口
	ClanMassMsgWindow             	= "GuiSystem.WindowList.Clan.ClanOwn.ClanMassMsgWindow"	,			--帮派群发消息窗口
	ClanPositionChgWindow           = "GuiSystem.WindowList.Clan.ClanOwn.ClanPositionChgWindow"	,		--帮派职位变更窗口
	ClanNameMdfWindow           	= "GuiSystem.WindowList.Clan.ClanOwn.ClanNameMdfWindow"	,			--帮派名称修改窗口
	ClanDeclareMdfWindow           	= "GuiSystem.WindowList.Clan.ClanOwn.ClanDeclareMdfWindow"	,		--帮派声明修改窗口
	WelcomePopWindow           		= "GuiSystem.WindowList.Clan.ClanOwn.WelcomePopWindow"	,			--帮派声明修改窗口
	BossHPWindow					= "GuiSystem.WindowList.BossHPWindow",					-- boss血条
	TaskTargetDirIconWindow			= "GuiSystem.WindowList.TaskTargetDirIconWindow",		--任务目标朝向窗口
	ConfirmPopWindow          		= "GuiSystem.WindowList.CommonWindow.ConfirmPopWindow",	-- 通用确认弹出框窗口
	InputPopWindow          		= "GuiSystem.WindowList.CommonWindow.InputPopWindow",	-- 通用输入确认弹出框窗口
	SkillReliveWindow				= "GuiSystem.WindowList.SkillReliveWindow",			-- 技能复活窗口
	FriendEmailWindow				= "GuiSystem.WindowList.FriendEmailWindow",			-- 好友邮件窗口
	TeamInvitedRespondWindow 		= "GuiSystem.WindowList.TeamInvitedRespondWindow",	-- 组队邀请相应窗口
	CommonRespondWindow             = "GuiSystem.WindowList.CommonWindow.CommonRespondWindow",-- 通用回复窗口
	CommonPrizeWindow				= "GuiSystem.WindowList.CommonPrizeWindow",			-- 任务奖励界面窗口
	SettingsWindow					= "GuiSystem.WindowList.SettingsWindow",			-- 设置窗口
	BuffTooltipsWindow				= "GuiSystem.WindowList.BuffTooltipsWindow",		-- Buff信息窗口
	EctypeTimerWindow				= "GuiSystem.WindowList.EctypeTimerWindow",			-- 时间倒计时窗口
	WelfareWindow                   = "GuiSystem.WindowList.WelfareWindow",             -- 福利窗口
	EctypeTreeWindow				= "GuiSystem.WindowList.EctypeTreeWindow",			-- 时间倒计时窗口
	PlayerSkillWindow				= "GuiSystem.WindowList.PlayerSkillWindow",			-- 玩家技能窗口
	LiuPaiSkillTipWindow			= "GuiSystem.WindowList.LiuPaiSkillTipWindow",		-- 流派技能提示弹窗
	LoungeWindow					= "GuiSystem.WindowList.LoungeWindow",				-- 休息室窗口
	JingJieDetailWindow				= "GuiSystem.WindowList.JingJieDetailWindow",		-- 境界详情窗口
	WuXueDetailWindow				= "GuiSystem.WindowList.WuXueDetailWindow",			-- 武学详情窗口
	ExchangeWindow					= "GuiSystem.WindowList.ExchangeWindow",			-- 交易窗口
	FreightTaskWindow				= "GuiSystem.WindowList.FreightTaskWindow",			-- 货运任务界面
	HGLYWindow						= "GuiSystem.WindowList.HGLYWindow",				-- 火攻粮营界面
	HGLYRankWindow					= "GuiSystem.WindowList.HuoGongLiangYing.HGLYRankWindow",		-- 火攻粮营排行榜界面
	SubTitleWindow 					= "GuiSystem.WindowList.SubTitleWindow",			-- 剧情旁白窗口
	MenPaiIconWindow				= "GuiSystem.WindowList.MenPaiIconWindow",			-- 门派入侵ICON窗口
	MenPaiWindow					= "GuiSystem.WindowList.HuoDongMenPai.MenPaiWindow",				-- 门派入侵窗口
	ExchangeSearchWindow			= "GuiSystem.WindowList.ExchangeSearchWindow",		-- 交易搜索窗口
	ExchangeBuyConfirmWindow		= "GuiSystem.WindowList.ExchangeBuyConfirmWindow",		-- 摆摊购买确认窗口
	GemConvertWindow				= "GuiSystem.WindowList.GemConvertWindow",			-- 宝石转换窗口
	PeachFeastWindow                = "GuiSystem.WindowList.PeachFeastWindow",          -- 蟠桃盛宴窗口
	PeachFeastRankWindow            = "GuiSystem.WindowList.PeachFeastRankWindow",      -- 蟠桃盛宴排行榜窗口
	ExchangePutGoodsWindow			= "GuiSystem.WindowList.ExchangePutGoodsWindow",	-- 交易物上架窗口
	ExchangeHistoryWindow			= "GuiSystem.WindowList.ExchangeHistoryWindow",		-- 交易记录查看窗口
    AuctionRecordWindow              = "GuiSystem.WindowList.AuctionRecordWindow",         -- 拍卖日志记录窗口
	FuMoTouPlayWindow				= "GuiSystem.WindowList.FuMoTouPlayWindow",			-- 伏魔骰投掷界面
	FuMoTouWindow					= "GuiSystem.WindowList.FuMoTouWindow",				-- 伏魔骰界面
	FuMoTouResultWindow				= "GuiSystem.WindowList.FuMoTouResultWindow",		-- 伏魔骰结果界面
	LigeFlagEditWindow				= "GuiSystem.WindowList.Clan.ClanOwn.LigeFlagEditWindow",	-- 帮会领地旗帜编辑窗口
	LigeLogbuchWindow				= "GuiSystem.WindowList.Clan.ClanOwn.LigeLogbuchWindow",	-- 帮会领地战况窗口
	LigeanceEntryWindow				= "GuiSystem.WindowList.Clan.ClanOwn.LigeanceEntryWindow",	-- 帮会领地战入口窗口
	DeclareWarInputWindow			= "GuiSystem.WindowList.Clan.ClanOwn.DeclareWarInputWindow",	-- 帮会领地宣战输入窗口
	ServerSelectWindow				= "GuiSystem.WindowList.ServerSelectWindow",				-- 服务器选择窗口
	ResAdjustWindow					= "GuiSystem.WindowList.ResAdjustWindow",			--等级封印窗口
	LigeanceFightWindow				= "GuiSystem.WindowList.LigeanceFightWindow",		--领地战战斗窗口
	LigeBalanceWindow				= "GuiSystem.WindowList.LigeBalanceWindow",		    --领地战战斗结束窗口
	ClanTransWindow                 = "GuiSystem.WindowList.ClanTransWindow",                   -- 帮会押运状态窗口
	ClanGoodsAddWindow              = "GuiSystem.WindowList.ClanGoodsAddWindow",				-- 帮会押运补充物资窗口
	BusinessWindow					= "GuiSystem.WindowList.BusinessWindow",					--跑商窗口
	GaoChangFightWindow				= "GuiSystem.WindowList.GaoChangFightWindow",				--高昌密道战斗窗口
	RedPacketWindow					= "GuiSystem.WindowList.RedPacketWindow",					--红包窗口
	RedPacketDetailWindow			= "GuiSystem.WindowList.RedPacketDetailWindow",					--红包详细信息窗口
	SceneRoleInfoWindow             = "GuiSystem.WindowList.SceneRoleInfoWindow",				--查看角色信息窗口 
	ClanShrineWindow				= "GuiSystem.WindowList.Clan.ClanBuilding.ClanShrineWindow",--帮会建筑主殿窗口
	ClanAcademyWindow				= "GuiSystem.WindowList.Clan.ClanBuilding.ClanAcademyWindow",--帮会技能升级窗口
	ClanWelfareWindow				= "GuiSystem.WindowList.Clan.ClanBuilding.ClanWelfareWindow",--帮会福利殿窗口
	ClanPresbyterWindow				= "GuiSystem.WindowList.Clan.ClanBuilding.ClanPresbyterWindow",--帮会长老殿窗口
	ClanWarfareWindow				= "GuiSystem.WindowList.Clan.ClanBuilding.ClanWarfareWindow",--帮会战争坊窗口
	--ClanTresonWindow				= "GuiSystem.WindowList.Clan.ClanBuilding.ClanTresonWindow",--帮会珍宝阁窗口
	HeadTalkBubbleWindow            = "GuiSystem.WindowList.HeadTalkBubbleWindow",				-- 头顶泡泡窗口
	FollowConfirmWindow             = "GuiSystem.WindowList.FollowConfirmWindow",				-- 召唤跟随响应窗口
	ExtendedConfirmWindow            = "GuiSystem.WindowList.ExtendedConfirmWindow",--宝石确认窗口
	MainRedPacketWindow             = "GuiSystem.WindowList.MainRedPacketWindow", --红包窗口
	QingGongStrengthWindow			= "GuiSystem.WindowList.QingGongStrengthWindow",			-- 轻功气力值窗口
	XiaKeXingBagWindow				= "GuiSystem.WindowList.XiaKeXingBagWindow",				-- 侠客行点赞礼包窗口
	WulinHeroWindow					= "GuiSystem.WindowList.WulinHeroWindow",					-- 武林英雄窗口
	UserAgreementWindow				= "GuiSystem.WindowList.UserAgreementWindow",				-- 用户协议
	GongGaoWindow					= "GuiSystem.WindowList.GongGaoWindow",						-- 公告
	CommonConfirmWindow				= "GuiSystem.WindowList.CommonConfirmWindow",				-- 带勾选不在提示确认窗口
    EntryConfigWindow               = "GuiSystem.WindowList.EntryConfigWindow",                 -- 服务器入口文件下载窗口
	HeadTitleUpGradeSuccessWindow   = "GuiSystem.WindowList.HeadTitleUpGradeSuccessWindow",     --头衔晋升成功界面
	TeamShowPanelLeaderClickWindow  = "GuiSystem.WindowList.TeamShowPanelLeaderClickWindow",	--操作队伍成员界面
	PlayerEffectWindow              = "GuiSystem.WindowList.PlayerEffectWindow",				--播放特效窗口
	AppearanceWindow				= "GuiSystem.WindowList.AppearanceWindow",					-- 外观窗口
	BossWindow                      = "GuiSystem.WindowList.BossWindow",                        -- 首领活动窗口
	BabelWnd						= "GuiSystem.WindowList.BabelWnd",							-- 通天塔界面
	BabelEndWnd						= "GuiSystem.WindowList.BabelEndWnd",						-- 通天塔结算界面
	SublineWindow                   = "GuiSystem.WindowList.Subline.SublineWindow",             -- 分线窗口
    ArrestRobberWindow              = "GuiSystem.WindowList.ArrestRobber.ArrestRobberWindow",   -- 缉拿大盗窗口
    JRBattleRankWindow				= "GuiSystem.WindowList.JiaRenBattle.JRBattleRankWindow",	-- 假人战场排行榜界面
    JRBattleTimerWindow				= "GuiSystem.WindowList.JiaRenBattle.JRBattleTimerWindow",	-- 假人战场倒计时界面

 	DamageRankWindow                = "GuiSystem.WindowList.DamageRankWindow",                  -- 伤害统计窗口	
    TitleWindow						= "GuiSystem.WindowList.TitleWindow",						-- 称号窗口	
    WulinHeroFightResultWindow		= "GuiSystem.WindowList.WulinHeroFightResultWindow",		-- 武林英雄副本结算界面	
    LoadingStateWindow				= "GuiSystem.WindowList.LoadingStateWindow",				-- 登录状态界面	
	TameWindow						= "GuiSystem.WindowList.TameWindow",						-- 驯马窗口
    KillWindow				        = "GuiSystem.WindowList.Fight.KillWindow",				    -- 杀敌窗口（击败，连斩提示）
    SerialWinWindow                 = "GuiSystem.WindowList.Fight.SerialWinWindow",             -- 连胜窗口 
	SurvivalMatchWindow				= "GuiSystem.WindowList.SurvivalMatchWindow",				-- 雪域求生报名界面	 
    BatchUseItemWindow 				= "GuiSystem.WindowList.BatchUseItemWindow",				-- 物品批量使用界面	    
	PickUpItemWindow                = "GuiSystem.WindowList.PickUpItemWindow",	     			-- 雪域求生拾取界面
	ChickingMatchWindow				= "GuiSystem.WindowList.Chicking.ChickingMatchWindow",		-- 通用匹配界面
	RankCompetitionWindow			= "GuiSystem.WindowList.RankCompetitionWindow",				-- 3v3武林大会入口
	RankCompetition3V3Window		= "GuiSystem.WindowList.RankCompetition3V3Window",			-- 3v3武林大会匹配成功
	RankCompeteOutcomeWindow		= "GuiSystem.WindowList.RankCompeteOutcomeWindow",			-- 3v3武林大会结算
}

---------------------------------------------------------------------
-- 关闭后不销毁的窗体名称
GuiDontDestroyOnHideList = 
{
    PackWindow = 1  ,
    FightBloodWindow = 1 ,
    NameTitleWindow = 1 ,
	GrayBoxTestWindow = 1 ,
	GrayBoxTestTreeWindow = 1 ,
}