

NameTitleType = 
{	
	NameType_None = 0,
	NameType_Npc =1, 			--npc
	NameType_MyHero =2, 		--自己主角
	NameType_OtherHero =3,		--其他玩家
	NameType_Monster_Normal =4,	--普通怪物
	NameType_Monster_Boss = 5,	--Boss
	NameType_MyPet = 6,			--自己宠物
	NameType_OtherPet = 7,		--其他玩家宠物
	NameType_OtherCanAtkHero = 8, --其他可以攻击的玩家
	NameType_OtherCanAtkPet = 9, --其他可以攻击的宠物
	NameType_Monster_Elite = 10, --精英怪物
	NameType_Equipment = 11, 		-- 装备
	NameType_Leedchdom = 12, 		-- 物品
	NameType_GoodsMoney = 13, 		-- 银两
	NameType_CampA = 14, 		-- 战场阵营A
	NameType_CampB = 15, 		-- 战场阵营B
	NameType_CampC = 16, 		-- 战场阵营C
	
	
}

NAMEColor ={
	OtherCanAttkHeroGreen =   UIFunction.GetColor(64,61,246,255),
	OtherCanAttkHeroRed =   UIFunction.GetColor(255,0,0,255),
	}
--[[
	public enum Effect
	{
		None,
		Shadow,
		Outline,
		Outline8,
	}--]]

NameStyleCfg ={

	[NameTitleType.NameType_Npc] = {fontPath = "",
									fontsize = 30,
									FamilyFontSize = 32,
									AchiveFontSize = 32,
									effectType = UILabel.Effect.Outline8,
									FamilyEffectType = UILabel.Effect.Outline8,
									AchiveEffectType =UILabel.Effect.Outline8,
									outline = Vector2.New(2.5,2.5),
									FamilyOutline = Vector2.New(2.5,2.5),
									AchiveOutLine = Vector2.New(2.5,2.5),
									outlineFamilyColor = UIFunction.GetColor(0,36,81,255),
									outlineAchiveColor =UIFunction.GetColor(0,36,81,255),
									oulineColor =UIFunction.GetColor(4,67,3,255),
									nameColor = UIFunction.GetColor(158,252,89,255),
									FamilyNameColor =UIFunction.GetColor(159,236,251,255),
									AchiveNameColor =UIFunction.GetColor(159,236,251,255),
									HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
									HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
									HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
									bHPred = false,
									},
									
										
	[NameTitleType.NameType_MyHero] = { 
										fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(2.5,2.5),
										FamilyOutline = Vector2.New(2.5,2.5),
										AchiveOutLine = Vector2.New(2.5,2.5),
										outlineFamilyColor = UIFunction.GetColor(80,62,0,255),
										outlineAchiveColor =UIFunction.GetColor(0,36,81,255),
										oulineColor =UIFunction.GetColor(0,36,81,255),
										nameColor = UIFunction.GetColor(159,236,251,255),
										FamilyNameColor =UIFunction.GetColor(254,235,104,255),
										AchiveNameColor =UIFunction.GetColor(159,236,251,255),
										effectType = UILabel.Effect.Outline8,
										FamilyEffectType = UILabel.Effect.Outline8,
										AchiveEffectType =UILabel.Effect.Outline8,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = false,
										},
										
										
	[NameTitleType.NameType_OtherHero] = {fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(2.5,2.5),
										FamilyOutline = Vector2.New(2.5,2.5),
										AchiveOutLine = Vector2.New(2.5,2.5),
										outlineFamilyColor = UIFunction.GetColor(80,62,0,255),
										outlineAchiveColor =UIFunction.GetColor(0,36,81,255),
										oulineColor =UIFunction.GetColor(59,48,0,255),
										nameColor = UIFunction.GetColor(251,244,218,255),
										FamilyNameColor =UIFunction.GetColor(254,235,104,255),
										AchiveNameColor =UIFunction.GetColor(159,236,251,255),
										effectType = UILabel.Effect.Outline8,
										FamilyEffectType = UILabel.Effect.Outline8,
										AchiveEffectType =UILabel.Effect.Outline8,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = false,
										},
										
	[NameTitleType.NameType_Monster_Normal] = {fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(0,0),
										FamilyOutline = Vector2.New(0,0),
										AchiveOutLine = Vector2.New(0,0),
										outlineFamilyColor = UIFunction.GetColor(0,36,81,255),
										outlineAchiveColor =UIFunction.GetColor(0,36,81,255),
										oulineColor =UIFunction.GetColor(255,255,255,255),
										nameColor = UIFunction.GetColor(255,255,255,255),
										FamilyNameColor =UIFunction.GetColor(159,236,251,255),
										AchiveNameColor =UIFunction.GetColor(159,236,251,255),
										effectType = UILabel.Effect.None,
										FamilyEffectType = UILabel.Effect.None,
										AchiveEffectType =UILabel.Effect.None,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_02.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = true,
										},
										
	[NameTitleType.NameType_Monster_Boss] = {fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(0,0),
										FamilyOutline = Vector2.New(0,0),
										AchiveOutLine = Vector2.New(0,0),
										outlineFamilyColor = UIFunction.GetColor(0,36,81,255),
										outlineAchiveColor =UIFunction.GetColor(0,36,81,255),
										oulineColor =UIFunction.GetColor(255,255,255,255),
										nameColor = UIFunction.GetColor(255,255,255,255),
										FamilyNameColor =UIFunction.GetColor(159,236,251,255),
										AchiveNameColor =UIFunction.GetColor(159,236,251,255),
										effectType = UILabel.Effect.None,
										FamilyEffectType = UILabel.Effect.None,
										AchiveEffectType =UILabel.Effect.None,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = true,
										},
									
	[NameTitleType.NameType_MyPet] = {  
                                        fontPath = "",
                                        fontsize = 30,
                                        FamilyFontSize = 30,
                                        nameColor = UIFunction.GetColor(159,236,251,255),
                                        FamilyNameColor =UIFunction.GetColor(254,235,104,255),
                                        FamilyOutline = Vector2.New(2,2),
										outline = Vector2.New(2,2),
                                        outlineFamilyColor = UIFunction.GetColor(80,62,0,255),
                                        oulineColor =UIFunction.GetColor(0,36,81,255),
										effectType = UILabel.Effect.Outline8,
										FamilyEffectType = UILabel.Effect.Outline8,
										AchiveEffectType =UILabel.Effect.Outline8,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = false,
										},
                                                    
	[NameTitleType.NameType_OtherPet] = { fontPath = "",
                                        fontsize = 30,
                                        FamilyFontSize = 30,
                                        nameColor = UIFunction.GetColor(251,244,218,255),
										outline = Vector2.New(2,2),
                                        FamilyOutline = Vector2.New(2,2),
                                        FamilyNameColor =UIFunction.GetColor(254,235,104,255),
                                        outlineFamilyColor = UIFunction.GetColor(80,62,0,255),
                                        oulineColor = UIFunction.GetColor(59,48,0,255),
										effectType = UILabel.Effect.Outline8,
										
										FamilyEffectType = UILabel.Effect.Outline8,
										AchiveEffectType =UILabel.Effect.Outline8,
                                        HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = false,
										  },
										
	[NameTitleType.NameType_OtherCanAtkHero] = {nameColor =  UIFunction.GetColor(255,0,0,255), fontsize = 30,fontPath = "",
	                                    oulineColor =UIFunction.GetColor(79,0,0,255),
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outlineFamilyColor = UIFunction.GetColor(80,62,0,255),
										outlineAchiveColor =UIFunction.GetColor(0,36,81,255),										
										FamilyNameColor =UIFunction.GetColor(254,235,104,255),
										AchiveNameColor =UIFunction.GetColor(159,236,251,255),
										effectType = UILabel.Effect.Outline8,
										FamilyEffectType = UILabel.Effect.None,
										AchiveEffectType =UILabel.Effect.None,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = true,  
										},
										
	[NameTitleType.NameType_OtherCanAtkPet] = {
										nameColor = UIFunction.GetColor(255,0,0,255),
										fontsize = 30,fontPath = "",
										ouline = Vector2.New(2,2),
                                        FamilyFontSize = 30,
                                        outlineFamilyColor = UIFunction.GetColor(80,62,0,255),
										oulineColor = UIFunction.GetColor(79,0,0,255),
                                        FamilyNameColor =UIFunction.GetColor(254,235,104,255),
										effectType = UILabel.Effect.Outline8,
										FamilyEffectType = UILabel.Effect.None,
										AchiveEffectType =UILabel.Effect.None,
                                        HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = true, 
										},
	
	[NameTitleType.NameType_Monster_Elite] = {fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(0,0),
										FamilyOutline = Vector2.New(0,0),
										AchiveOutLine = Vector2.New(0,0),
										outlineFamilyColor = UIFunction.GetColor(0,36,81,255),
										outlineAchiveColor =UIFunction.GetColor(0,36,81,255),
										oulineColor =UIFunction.GetColor(255,255,255,255),
										nameColor = UIFunction.GetColor(255,255,255,255),
										FamilyNameColor =UIFunction.GetColor(159,236,251,255),
										AchiveNameColor =UIFunction.GetColor(159,236,251,255),
										effectType = UILabel.Effect.None,
										FamilyEffectType = UILabel.Effect.None,
										AchiveEffectType =UILabel.Effect.None,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = true,
										},
										
	[NameTitleType.NameType_Equipment] = {fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(0,0),
										FamilyOutline = Vector2.New(0,0),
										AchiveOutLine = Vector2.New(0,0),
										outlineFamilyColor = UIFunction.GetColor(0,36,81,255),
										outlineAchiveColor =UIFunction.GetColor(0,36,81,255),
										oulineColor =UIFunction.GetColor(255,255,255,255),
										nameColor = UIFunction.GetColor(255,255,255,255),
										FamilyNameColor =UIFunction.GetColor(159,236,251,255),
										AchiveNameColor =UIFunction.GetColor(159,236,251,255),
										effectType = UILabel.Effect.None,
										FamilyEffectType = UILabel.Effect.None,
										AchiveEffectType =UILabel.Effect.None,
										HpImagePath = ""
										},
										
	[NameTitleType.NameType_Leedchdom] = {fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(0,0),
										FamilyOutline = Vector2.New(0,0),
										AchiveOutLine = Vector2.New(0,0),
										outlineFamilyColor = UIFunction.GetColor(0,36,81,255),
										outlineAchiveColor =UIFunction.GetColor(0,36,81,255),
										oulineColor =UIFunction.GetColor(255,255,255,255),
										nameColor = UIFunction.GetColor(255,255,255,255),
										FamilyNameColor =UIFunction.GetColor(159,236,251,255),
										AchiveNameColor =UIFunction.GetColor(159,236,251,255),
										effectType =UILabel.Effect.None,
										FamilyEffectType = UILabel.Effect.None,
										AchiveEffectType =UILabel.Effect.None,
										HpImagePath =""
										},	
										
	[NameTitleType.NameType_GoodsMoney] = {fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(0,0),
										FamilyOutline = Vector2.New(0,0),
										AchiveOutLine = Vector2.New(0,0),
										outlineFamilyColor = UIFunction.GetColor(0,36,81,255),
										outlineAchiveColor =UIFunction.GetColor(0,36,81,255),
										oulineColor =UIFunction.GetColor(255,255,255,255),
										nameColor = UIFunction.GetColor(255,255,255,255),
										FamilyNameColor =UIFunction.GetColor(159,236,251,255),
										AchiveNameColor =UIFunction.GetColor(159,236,251,255),
										effectType = UILabel.Effect.None,
										FamilyEffectType =UILabel.Effect.None,
										AchiveEffectType =UILabel.Effect.None,
										HpImagePath = ""
										},
	
	[NameTitleType.NameType_CampA] = {fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(2.5,2.5),
										FamilyOutline = Vector2.New(2.5,2.5),
										AchiveOutLine = Vector2.New(2.5,2.5),
										outlineFamilyColor = UIFunction.GetColor(80,62,0,255),
										outlineAchiveColor =UIFunction.GetColor(82,38,0,255),
										oulineColor =UIFunction.GetColor(82,38,0,255),
										nameColor = UIFunction.GetColor(249,218,161,255),
										FamilyNameColor =UIFunction.GetColor(254,235,104,255),
										AchiveNameColor =UIFunction.GetColor(249,218,161,255),
										effectType = UILabel.Effect.Outline8,
										FamilyEffectType = UILabel.Effect.Outline8,
										AchiveEffectType =UILabel.Effect.Outline8,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = false,
										},
										
	[NameTitleType.NameType_CampB] = {fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(2.5,2.5),
										FamilyOutline = Vector2.New(2.5,2.5),
										AchiveOutLine = Vector2.New(2.5,2.5),
										
										outlineFamilyColor = UIFunction.GetColor(80,62,0,255),
										outlineAchiveColor =UIFunction.GetColor(103,0,118,255),
										oulineColor =UIFunction.GetColor(103,0,118,255),
										
										nameColor = UIFunction.GetColor(247,195,255,255),
										FamilyNameColor =UIFunction.GetColor(254,235,104,255),
										AchiveNameColor =UIFunction.GetColor(247,195,255,255),
										effectType = UILabel.Effect.Outline8,
										FamilyEffectType = UILabel.Effect.Outline8,
										AchiveEffectType =UILabel.Effect.Outline8,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = false,
										},
										
	[NameTitleType.NameType_CampC] = {fontPath = "",
										fontsize = 30,
										FamilyFontSize = 30,
										AchiveFontSize = 30,
										outline = Vector2.New(2.5,2.5),
										FamilyOutline = Vector2.New(2.5,2.5),
										AchiveOutLine = Vector2.New(2.5,2.5),
										outlineFamilyColor = UIFunction.GetColor(80,62,0,255),
										outlineAchiveColor =UIFunction.GetColor(5,32,3,255),
										oulineColor =UIFunction.GetColor(5,32,3,255),
										nameColor = UIFunction.GetColor(161,246,207,255),
										FamilyNameColor =UIFunction.GetColor(254,235,104,255),
										AchiveNameColor =UIFunction.GetColor(161,246,207,255),
										effectType = UILabel.Effect.Outline8,
										FamilyEffectType = UILabel.Effect.Outline8,
										AchiveEffectType =UILabel.Effect.Outline8,
										HpBgImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_0.png",
										HpImagePath = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_lv_2.png",
										HpImagePathRed = GuiAssetList.GuiRootTexturePath.."Fight/fighting_jidu_hon_2.png",
										bHPred = false,
										},
}